# MangoHud theme - gruvbox + Cozette vector (big)
font_file = /home/aa/.local/share/fonts/CozetteVector.ttf
font_size = 24

position = top-left

# gruvbox palette
background_color = 282828
text_color = ebdbb2

fps_color = d65d0e
cpu_color = fabd2f
gpu_color = 689d6a
vram_color = d3869b
ram_color = 83a598
engine_color = fb4934
io_color = 8ec07c
